# Generated by Django 3.2.8 on 2021-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20211205_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CountStars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Stars',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pics',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
